ALTER TABLE tb_Cadastro
ADD CONSTRAINT FK_AUTOR_CAD FOREIGN KEY (id_Autor) REFERENCES tb_Autor (id_Autor);

ALTER TABLE tb_Endereco
ADD CONSTRAINT FK_AUTOR_END FOREIGN KEY (id_Autor) REFERENCES tb_Autor (id_Autor);

ALTER TABLE tb_Telefone
ADD CONSTRAINT FK_AUTOR_TEL FOREIGN KEY (id_Autor) REFERENCES tb_Autor (id_Autor);

ALTER TABLE tb_Autoria
ADD CONSTRAINT FK_AUTOR_AUTORIA FOREIGN KEY (id_Autor) REFERENCES tb_Autor (id_Autor);
ALTER TABLE tb_Autoria
ADD CONSTRAINT FK_OBRA_AUTORIA FOREIGN KEY (id_Obra) REFERENCES tb_Obra (id_Obra);

ALTER TABLE tb_FormacaoAcademica
ADD CONSTRAINT FK_AUTOR_FORMAC FOREIGN KEY (id_Autor) REFERENCES tb_Autor (id_Autor);

ALTER TABLE tb_AreaObra
ADD CONSTRAINT FK_AREA_OBRA_TUDO FOREIGN KEY (id_Area) REFERENCES tb_AreaConhecimento (id_Area);

ALTER TABLE tb_VersaoRevisada
ADD CONSTRAINT FK_OBRA_VERS FOREIGN KEY (id_Obra) REFERENCES tb_Obra (id_Obra);
ALTER TABLE tb_VersaoRevisada
ADD CONSTRAINT FK_STATUS FOREIGN KEY (id_Status) REFERENCES tb_StatusObra (id_Status);

ALTER TABLE tb_Obra
ADD CONSTRAINT FK_AUTOR_OBRA FOREIGN KEY (id_Autor) REFERENCES tb_Autor (id_Autor);
ALTER TABLE tb_Obra
ADD CONSTRAINT FK_AREA_PRINC_OBRA FOREIGN KEY (id_Area) REFERENCES tb_AreaConhecimento (id_Area);
ALTER TABLE tb_Obra
ADD CONSTRAINT FK_REVISOR FOREIGN KEY (id_Revisor) REFERENCES tb_Revisor (id_Revisor);
ALTER TABLE tb_Obra
ADD CONSTRAINT FK_TIPO_OBRA FOREIGN KEY (id_Tipo) REFERENCES tb_TipoObra (id_Tipo);

ALTER TABLE tb_Avaliacao
ADD CONSTRAINT FK_PARCER_AVAL FOREIGN KEY (id_Parcerista) REFERENCES tb_Parcerista (id_Parcerista);
ALTER TABLE tb_Avaliacao
ADD CONSTRAINT FK_OBRA_AVAL FOREIGN KEY (id_Obra) REFERENCES tb_Obra (id_Obra);

ALTER TABLE tb_NotasAvaliacao
ADD CONSTRAINT FK_AVALIACAO FOREIGN KEY (id_Avaliacao) REFERENCES tb_Avaliacao (id_Avaliacao);
ALTER TABLE tb_NotasAvaliacao
ADD CONSTRAINT FK_ITEM_AVAL FOREIGN KEY (id_Item) REFERENCES tb_ItensAvaliacao (id_Item);